### ISSUE TITLE
Numbers in the cost breakdown section are sometimes printed as fractions

### ISSUE THREAD

**Issue by lexi-lambda** [stamourv/feature-profile#14]
Running this on some code of mine, I get the following output for the cost breakdown section:

```
Cost Breakdown
  47 ms : map/m (-> (-> any/c monad?) sequence? monad?)
  25/2 ms : space/p (or/c (struct/c delayed-pure char?) (struct/c parser (-> any/c (or/c (struct/c consumed (or/c error? (struct/c ok char? any/c message?))) (struct/c empty (or/c error? (struct/c ok char? any/c message?)))))))
  23/2 ms : length (-> countable? exact-nonnegative-integer?)
  10 ms : satisfy/p (-> (-> any/c any/c) parser?*)
```

Note the `25/2` and `23/2` numbers. This is an area where printing fractions is more harmful than helpful, since it makes quickly scanning the list of durations somewhat difficult, so some explicit logic to ensure they are printed as decimals is probably in order.

**Comment by stamourv** [comment]
Oh, ugh. I thought I fixed those.
Exact rationals are one of those things that, on paper, really look like the Right Thing™ but, in practice, are almost never what you want.
