### ISSUE TITLE
Cannot install on 6.2.1

### ISSUE THREAD

**Issue by bennn** [stamourv/feature-profile#17]
Just tried to `raco pkg install feature-profile` with a `raco`from Racket v6.2.1. Here's part of the error message

```
raco setup: --- summary of errors ---
raco setup: error: during making for <pkgs>/feature-profile
raco setup:   /Users/ben/Library/Racket/6.2.1/pkgs/feature-profile/profile-helpers.rkt:97:11: group-by: unbound identifier in module
raco setup:     in: group-by
raco setup:     compiling: <pkgs>/feature-profile/profile-helpers.rkt
```

- - -

(This issue isn't serious for me, so I care enough to report it but not to submit a PR)

**Comment by stamourv** [comment]
The easy fix would be to add a dependency on the right version of base to feature-profile.
Alternatively, if you do need to run the FSP on 6.2.1, I could add a version exception. Assuming that 6.2.1 has everything else that it needs.

**Comment by bennn** [comment]
The easy fix is ok with me.

**Comment by stamourv** [comment]
Fixed. Thanks for the report!
